# Generated by Django 4.1.5 on 2023-01-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='about',
        ),
    ]
