# Generated by Django 4.1.5 on 2023-01-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollador', '0002_rename_name_about_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='Skill',
        ),
    ]
