# Generated by Django 4.1.5 on 2023-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollador', '0003_rename_contacts_contact_rename_projects_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(),
        ),
    ]
