# Generated by Django 4.1.5 on 2023-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollador', '0005_alter_contact_image_alter_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
