# Generated by Django 4.1.5 on 2023-01-19 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollador', '0006_alter_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
